version: '3.8'

# Define services.
services:
  # Service for the 'default' Go backend.
  default:
    # Configuration for building the Docker image for the service.
    build:
      # Use an image built from the specified Dockerfile in the current directory.
      context: .
      dockerfile: Dockerfile
    # Set restart rules for the container.
    restart: unless-stopped
    # Forward the exposed port 8080 on the container to port 8080 on the host machine.
    ports:
      - '8080:8080'
    # Set needed environment variables for the Go backend.
    environment:
      BACKEND_PORT: 8080 # same as the exposed container port
    # Networks to join.
    # Services on the same network can communicate with each other using their name.
    networks:
      - default_network

# Define Docker networks.
networks:
  # Create default network.
  default_network:
